"""MARSOUD-QTY-3DP (2026-08-17) — widen quantity/weight columns from
Numeric(x, 2) to Numeric(x, 3) so weight-based businesses (silversmiths,
goldsmiths, meat, spices) can record third-decimal grams / kg.

The change is BACKWARD-COMPATIBLE for existing 2-decimal users: their
values keep saving as x.xx, just now with room for a trailing 0 in the
third position. It's forward-compatible for new 3-decimal users:
23.475 now stores exactly instead of rounding to 23.48.

Money columns are NOT touched — this is quantity/weight only.

Touched columns:
  · invoice_items.quantity         Numeric(10, 2) → (10, 3)
  · vendor_bill_items.quantity     Numeric(10, 2) → (10, 3)
  · stock_balances.qty             Numeric(15, 2) → (15, 3)
  · stock_balances.piece_count     Numeric(15, 2) → (15, 3)
  · stock_movements.qty_delta      Numeric(15, 2) → (15, 3)
  · stock_movements.balance_qty_after Numeric(15,2) → (15,3)
  · stock_lots.qty                 Numeric(15, 2) → (15, 3)
  · stock_lots.qty_remaining       Numeric(15, 2) → (15, 3)
  · stock_transfer_items.qty       Numeric(15, 2) → (15, 3)
  · inventory_counts.book_qty      Numeric(15, 2) → (15, 3)
  · inventory_counts.book_pieces   Numeric(15, 2) → (15, 3)
  · inventory_counts.counted_qty   Numeric(15, 2) → (15, 3)
  · inventory_counts.counted_pieces Numeric(15,2) → (15, 3)
  · inventory_counts.variance_qty  Numeric(15, 2) → (15, 3)
  · inventory_counts.variance_pieces Numeric(15,2) → (15, 3)
  · product_variants.reorder_level Numeric(15, 2) → (15, 3)

Idempotent: uses `alter_column` with `existing_type` matching what
Alembic autogenerated. For SQLite the batch mode rebuilds the table
in place — safe. For Postgres this is a metadata-only change.

Revision ID: j7k0l3m6n9p2
Revises: i5j8k1l4m7n0
Create Date: 2026-08-17
"""
from alembic import op
import sqlalchemy as sa


revision = "j7k0l3m6n9p2"
down_revision = "i5j8k1l4m7n0"
branch_labels = None
depends_on = None


# (table, column, existing_default)
COLS = [
    ("invoice_items",       "quantity",              sa.Numeric(10, 2), sa.text("1")),
    ("vendor_bill_items",   "quantity",              sa.Numeric(10, 2), sa.text("1")),
    ("stock_balances",      "qty",                   sa.Numeric(15, 2), sa.text("0")),
    ("stock_balances",      "piece_count",           sa.Numeric(15, 2), sa.text("0")),
    ("stock_movements",     "qty_delta",             sa.Numeric(15, 2), None),
    ("stock_movements",     "balance_qty_after",     sa.Numeric(15, 2), sa.text("0")),
    ("stock_lots",          "qty",                   sa.Numeric(15, 2), None),
    ("stock_lots",          "qty_remaining",         sa.Numeric(15, 2), sa.text("0")),
    ("stock_transfer_items", "qty",                  sa.Numeric(15, 2), None),
    ("inventory_counts",    "book_qty",              sa.Numeric(15, 2), None),
    ("inventory_counts",    "book_pieces",           sa.Numeric(15, 2), sa.text("0")),
    ("inventory_counts",    "counted_qty",           sa.Numeric(15, 2), None),
    ("inventory_counts",    "counted_pieces",        sa.Numeric(15, 2), sa.text("0")),
    ("inventory_counts",    "variance_qty",          sa.Numeric(15, 2), sa.text("0")),
    ("inventory_counts",    "variance_pieces",       sa.Numeric(15, 2), sa.text("0")),
    ("product_variants",    "reorder_level",         sa.Numeric(15, 2), sa.text("0")),
]


def _inspector():
    return sa.inspect(op.get_bind())


def _has_column(table, col):
    try:
        insp = _inspector()
        if table not in insp.get_table_names():
            return False
        return any(c["name"] == col for c in insp.get_columns(table))
    except Exception:
        return False


def upgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    for table, col, existing_type, _default in COLS:
        if not _has_column(table, col):
            continue
        new_type = sa.Numeric(existing_type.precision, 3)
        # SQLite needs batch mode; Postgres/MySQL take a plain ALTER.
        if dialect == "sqlite":
            with op.batch_alter_table(table) as batch:
                batch.alter_column(
                    col, existing_type=existing_type, type_=new_type,
                    existing_nullable=False,
                )
        else:
            op.alter_column(
                table, col,
                existing_type=existing_type, type_=new_type,
                existing_nullable=False,
            )


def downgrade():
    bind = op.get_bind()
    dialect = bind.dialect.name

    for table, col, _prev_type, _default in COLS:
        if not _has_column(table, col):
            continue
        old_type = sa.Numeric(_prev_type.precision, 2)
        new_type = sa.Numeric(_prev_type.precision, 3)
        if dialect == "sqlite":
            with op.batch_alter_table(table) as batch:
                batch.alter_column(
                    col, existing_type=new_type, type_=old_type,
                    existing_nullable=False,
                )
        else:
            op.alter_column(
                table, col,
                existing_type=new_type, type_=old_type,
                existing_nullable=False,
            )
