"""MARSOUD-VIOLATION-POLICY (2026-08-05) — ticket 6.

Two new tables plus one column on an existing one:

  1. attendance_violation_policies — the rates (unexcused/excused
     absence, monthly late-minute pool, per-day cap, permission count
     and max hours). Scoped like AttendancePolicy: company / department /
     employee.

  2. late_permission_requests — an employee's request to arrive late
     (or leave early) on a single day. Mirrors leave_requests: PENDING /
     APPROVED / REJECTED / CANCELLED, reviewer + timestamp + note.

  3. attendance_exceptions.is_excused — a boolean per exception, only
     ever READ when the type is ABSENT or UNPAID_LEAVE. Defaults false
     so every existing row reads as "unexcused", which combined with
     "no policy → 1.0 day either way" keeps every existing payroll
     number identical.

WHY THIS PATH RATHER THAN batch_alter_table ON attendance_exceptions.
Handoff fact 4: this table carries an inline unnamed CHECK generated by
the `type` Enum column. batch refuses it — "Constraint must have a
name" — and a naming_convention does not reach a reflected CHECK. The
column is a plain Boolean with a server default, no FK, so a straight
add_column works on every backend and no rebuild is needed.

WHY WE DO NOT RE-CREATE `policyscope`. The enum already exists from
n4w7s0y3r8t9_attendance_policies. Postgres would reject a second CREATE
TYPE; using create_type=False on the reused enum tells alembic to
reference the existing type rather than create it. SQLite uses stored
strings for enums so the flag is a no-op there.

Every add is guarded by an existence check so a half-applied run
completes on the next pass — the same shape as
q7z0v3b6u1w2_exception_soft_delete.

Revision ID: r0y5c8v2n1p3
Revises: q7z0v3b6u1w2
Create Date: 2026-08-05
"""
from alembic import op
import sqlalchemy as sa


revision = 'r0y5c8v2n1p3'
down_revision = 'q7z0v3b6u1w2'
branch_labels = None
depends_on = None


TABLE_VP = "attendance_violation_policies"
TABLE_LP = "late_permission_requests"
TABLE_EX = "attendance_exceptions"

# Reuse the enum ticket 1 created. create_type=False on Postgres avoids
# a duplicate CREATE TYPE; SQLite stores strings and ignores the flag.
SCOPE = sa.Enum("COMPANY", "DEPARTMENT", "EMPLOYEE",
                name="policyscope", create_type=False)
PSTATUS = sa.Enum("PENDING", "APPROVED", "REJECTED", "CANCELLED",
                  name="permissionstatus")


def _has_table(name):
    return name in sa.inspect(op.get_bind()).get_table_names()


def _cols(table):
    insp = sa.inspect(op.get_bind())
    if table not in insp.get_table_names():
        return set()
    return {c["name"] for c in insp.get_columns(table)}


def upgrade():
    bind = op.get_bind()

    # 1. attendance_violation_policies
    if not _has_table(TABLE_VP):
        op.create_table(
            TABLE_VP,
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("company_id", sa.Integer,
                      sa.ForeignKey("companies.id", ondelete="CASCADE"),
                      nullable=False, index=True),
            sa.Column("scope", SCOPE, nullable=False,
                      server_default="COMPANY", index=True),
            sa.Column("department_id", sa.Integer,
                      sa.ForeignKey("departments.id", ondelete="CASCADE"),
                      nullable=True, index=True),
            sa.Column("employee_id", sa.Integer,
                      sa.ForeignKey("employees.id", ondelete="CASCADE"),
                      nullable=True, index=True),
            sa.Column("absence_unexcused_deduction_days", sa.Numeric(4, 2),
                      nullable=False, server_default="1.00"),
            sa.Column("absence_excused_deduction_days", sa.Numeric(4, 2),
                      nullable=False, server_default="1.00"),
            sa.Column("monthly_free_late_minutes", sa.Integer,
                      nullable=False, server_default="0"),
            sa.Column("daily_free_late_minutes_cap", sa.Integer,
                      nullable=False, server_default="0"),
            sa.Column("permission_count_per_month", sa.Integer,
                      nullable=False, server_default="0"),
            sa.Column("permission_max_hours", sa.Numeric(4, 2),
                      nullable=False, server_default="0.00"),
            sa.Column("is_active", sa.Boolean, nullable=False,
                      server_default=sa.true(), index=True),
            sa.Column("created_at", sa.DateTime),
            sa.Column("created_by", sa.Integer,
                      sa.ForeignKey("users.id")),
        )

    # 2. late_permission_requests
    if not _has_table(TABLE_LP):
        op.create_table(
            TABLE_LP,
            sa.Column("id", sa.Integer, primary_key=True),
            sa.Column("company_id", sa.Integer,
                      sa.ForeignKey("companies.id"),
                      nullable=False, index=True),
            sa.Column("employee_id", sa.Integer,
                      sa.ForeignKey("employees.id"),
                      nullable=False, index=True),
            sa.Column("request_date", sa.Date, nullable=False),
            sa.Column("start_time", sa.Time),
            sa.Column("end_time", sa.Time),
            sa.Column("hours_count", sa.Numeric(4, 2),
                      nullable=False, server_default="0"),
            sa.Column("reason", sa.Text),
            sa.Column("status", PSTATUS, nullable=False,
                      server_default="PENDING", index=True),
            sa.Column("reviewed_by", sa.Integer,
                      sa.ForeignKey("users.id")),
            sa.Column("reviewed_at", sa.DateTime),
            sa.Column("review_note", sa.Text),
            sa.Column("created_at", sa.DateTime),
            sa.Column("created_by", sa.Integer,
                      sa.ForeignKey("users.id")),
        )

    # 3. attendance_exceptions.is_excused
    if _has_table(TABLE_EX) and "is_excused" not in _cols(TABLE_EX):
        op.add_column(TABLE_EX, sa.Column(
            "is_excused", sa.Boolean, nullable=False,
            server_default=sa.false()))


def downgrade():
    bind = op.get_bind()
    if "is_excused" in _cols(TABLE_EX):
        # attendance_exceptions is the batch-hostile table (fact 4). A
        # plain drop_column works on Postgres; SQLite would rebuild via
        # batch, but batch refuses this table. We do our best on both:
        # try the plain drop first and fall through on SQLite.
        try:
            op.drop_column(TABLE_EX, "is_excused")
        except Exception:
            pass
    if _has_table(TABLE_LP):
        op.drop_table(TABLE_LP)
    if _has_table(TABLE_VP):
        op.drop_table(TABLE_VP)
    if bind.dialect.name == "postgresql":
        PSTATUS.drop(bind, checkfirst=True)
